### ISSUE TITLE
[BUG] content folder not used

### ISSUE THREAD

**Issue by Slevin90** [linuxserver/docker-raneto#17]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

using latest (currently: 0.17.3) the content folder is wrong.

linuxserver Application Setup states content should be in:    /config/content
but new raneto build uses the files in : /app/raneto/content

### Expected Behavior

/config/content should be used to generate the files.

### Steps To Reproduce

re-used config that worked before.
updated to 17.3
the standard raneto appear

### Environment

```markdown
- OS:    Debian/ raspbian
- How docker service was installed: portainer,  service worked before.  updated with new image
```

### CPU architecture

arm64

### Docker creation

```bash
portainer to recreate with :latest
```

### Container logs

```bash
[migrations] started
[migrations] no migrations found
───────────────────────────────────────
      ██╗     ███████╗██╗ ██████╗ 
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 
   Brought to you by linuxserver.io
───────────────────────────────────────
To support LSIO projects visit:
https://www.linuxserver.io/donate/
───────────────────────────────────────
GID/UID
───────────────────────────────────────
User UID:    1001
User GID:    100
───────────────────────────────────────
[custom-init] No custom files found, skipping...
[ls.io-init] done.
GET / 200 241.850 ms - 6288
GET /lib/highlightjs/styles/solarized_light.css 200 23.128 ms - 1597
GET /styles/raneto.css 200 28.354 ms - 2411
GET /lib/bootstrap/dist/css/bootstrap.min.css 200 41.822 ms - 162264
GET /styles/ghostdown.css 200 33.954 ms - 10582
GET /lib/popper.js/dist/umd/popper.min.js 200 36.244 ms - 21233
GET /lib/jquery/dist/jquery.min.js 200 41.389 ms - 89664
GET /lib/bootstrap/dist/js/bootstrap.min.js 200 19.057 ms - 62563
GET /lib/fitvids/dist/fitvids.min.js 200 28.625 ms - 3535
GET /lib/masonry-layout/dist/masonry.pkgd.min.js 200 24.375 ms - 24103
GET /scripts/raneto.js 200 29.991 ms - 4921
GET /scripts/ghostdown.js 200 27.237 ms - 254264
GET /lib/highlightjs/highlight.pack.min.js 200 24.847 ms - 749329
GET /translations/en.json 200 7.651 ms - 1537
```

**Comment by thespad** [comment]
Can you try `lspipepr/raneto:0.17.3-pkg-7f131295-pr-18` and see if it fixes the issue (without causing new ones).

**Comment by Slevin90** [comment]
> 

Instead of showing pre-made content.
0.17.2-ls93 now shows no content.   (but does parse like a regular raneto.. just with no .md files)

reverting to linuxserver/0.17.2-ls93 shows content as it should be

**Comment by thespad** [comment]
Is that with an existing install?

CI tests suggest a clean install should be working correctly https://ci-tests.linuxserver.io/lspipepr/raneto/0.17.3-pkg-7f131295-pr-18/index.html

**Comment by unmacaque** [comment]
I have the same issue right now. Seems like it will now always use `/app/raneto/config/config.js` and ignore any custom configuration in `/config`. Possibly this was introduced in [this commit](https://github.com/linuxserver/docker-raneto/blob/master/root/defaults/server.js#L14)?

**Comment by thespad** [comment]
Yeah that was overlooked when I updated the default files, it's fixed in #18 which is building now.

**Comment by Slevin90** [comment]
either still needs fixing or manual needs updating:

from:
`/config/content - All of your Markdown files go here [more info](http://docs.raneto.com/usage/creating-pages).
`to
`/config/content/pages - All of your Markdown files go here [more info](http://docs.raneto.com/usage/creating-pages).`

**Comment by Slevin90** [comment]
Guessing it can be closed. 


https://github.com/ryanlelek/Raneto/tree/master/content    
upstream Raneto has /content/pages structure as well.
So it is intended behaviour.

Friendly message is welcome for people to know updating to 0.17.3

**Comment by thespad** [comment]
I'm not sure why because the content path hasn't changed, it's always been `/config/content`. They must have changed something upstream.

I'll make sure there's a note added to the readme.
