### ISSUE TITLE
missing default config

### ISSUE THREAD

**Issue by steveb85** [linuxserver/docker-raneto#24]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

hey, excellent app, really nicely done, thanks. 

heads up, the 

show_on_home_menu: true,

is missing in the default config, and led to a bit of head scratching as the side menu doesn't generate or do anything until you add this in, maybe easier for new users to ensure it's in there even if set to false, - when building as a docker this is, so perhaps different from a standard install, just a heads up. 
thanks all! 

### Expected Behavior

show_on_home_menu: true,

### Steps To Reproduce

install

### Environment

```markdown
- OS:aks docker
- How docker service was installed:
yaml
```

### CPU architecture

x86-64

### Docker creation

```bash
na
```

### Container logs

```bash
na
```

**Comment by TG-March** [comment]
The correct section to add to the config.default.js is described below (the OP's comment has the wrong info):

  // Controls behavior of the menu if meta ShowOnMenu is not present. If set to true
  // all categories or files that do not specify ShowOnMenu meta property will be shown
  show_on_menu_default: true,

This was not included in the config.default.js when I installed image with tag `:latest` today.
