### ISSUE TITLE
"Error Saving Page" in subfolders

### ISSUE THREAD

**Issue by rbnhln** [linuxserver/docker-raneto#8]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

Error by edeting markdown-files in the webinterface depending on subfolder location. 

------------------------------

## Expected Behavior
The error occurs if I try to edit a MD-File in the webinterface. It works if the MD file is located under 
/config/content/example/test.md. If the file is moved one level down e.g. to /config/content/example/subfolder/test.md it can no longer be edited.
## Current Behavior
Error message displayed by hitting save: "Error Saving Page"

## Steps to Reproduce

1. Create a MD-File under /config/content/example/test.md
2. Edeting in webinterface works
3. Moving fole to /config/content/example/subfolder/test.md
4. Edeting in webinterface fails

## Environment
**OS:**      ubuntu 19.10 / ubuntu 18.04
**CPU architecture:** x86_64      
**How docker service was installed:** apt / offical docker-repo     

## Command used to create docker container (run/create/compose/screenshot)
compose.yml

## Docker logs

If it fails:
POST /rn-edit 200 1.712 ms - 108
If it works:
POST /rn-edit 200 7.503 ms - 35

**Comment by thelamer** [comment]
Yep it sure does, though this needs to be reported upstream.
you might want to piggyback on this issue: 
https://github.com/gilbitron/Raneto/issues/188
We only wrap this software in a docker container, and this is something outside of our control.
